language: python
python: "2.7"

install: pip install tox

before_script: sudo update-alternatives --install /bin/sh sh /bin/bash 100

script: tox

after_script:
    - ps -efl > var/log/ps.out
    - bash tests/scripts/pretty_print.bash

after_success:
    - pip install coveralls
    - coveralls
